Remove FunctionCallGraph.cpp's dependence on StringUtils.h due to an error in the Windows build
The Windows build errors include:
...
libsolutil/StringUtils.h(62,21): error : reference to 'end' is ambiguous
...
libsolutil/StringUtils.h(66,17): error : reference to 'begin' is ambiguous

I'm not sure why there's no namespace specification for `begin` and
`end` in StringUtils.h and also how the Windows build was fine for 0.7.1
(which also doesn't have the aforementioned namespace specification)